#ifndef COMMUNICATION_PROTOCOL_HPP
#define COMMUNICATION_PROTOCOL_HPP


//TODO MOVE ALL DEFINITIONS TO OTHER FILE?
namespace UVO_CommunicationProtocol {

	const int MAIN_CONTROLLER_ADDRESS = 40;
	const int LED_CONTROLLER_ADDRESS = 60;
	const int MOTOR_CONTROLLER_ADDRESS = 80;

	const char REQUEST_SENSOR_DATA_IDENTIFIER = 'S';


}

#endif